# Generated by Django 4.2.17 on 2025-01-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_category_product_catageory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catageory',
            new_name='catagory',
        ),
    ]
