# Generated by Django 4.2.17 on 2025-01-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
